package com.delivery.entity;
// Generated 07-15-2020 03:28:48 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Motociclista generated by hbm2java
 */
@Entity
@Table(name = "motociclista", catalog = "delivery")
public class Motociclista implements java.io.Serializable {

	private Integer idMotociclista;
	private Personal personal;
	private Unidad unidad;
	private String poseeMoto;
	private List<Ruta> rutas = new ArrayList<Ruta>(0);

	public Motociclista() {
	}

	public Motociclista(Personal personal, Unidad unidad, String poseeMoto) {
		this.personal = personal;
		this.unidad = unidad;
		this.poseeMoto = poseeMoto;
	}

	public Motociclista(Personal personal, Unidad unidad, String poseeMoto, List<Ruta> rutas) {
		this.personal = personal;
		this.unidad = unidad;
		this.poseeMoto = poseeMoto;
		this.rutas = rutas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_motociclista", unique = true, nullable = false)
	public Integer getIdMotociclista() {
		return this.idMotociclista;
	}

	public void setIdMotociclista(Integer idMotociclista) {
		this.idMotociclista = idMotociclista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_personal", nullable = false)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_unidad", nullable = false)
	public Unidad getUnidad() {
		return this.unidad;
	}

	public void setUnidad(Unidad unidad) {
		this.unidad = unidad;
	}

	@Column(name = "posee_moto", nullable = false, length = 3)
	public String getPoseeMoto() {
		return this.poseeMoto;
	}

	public void setPoseeMoto(String poseeMoto) {
		this.poseeMoto = poseeMoto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motociclista")
	public List<Ruta> getRutas() {
		return this.rutas;
	}

	public void setRutas(List<Ruta> rutas) {
		this.rutas = rutas;
	}

}
