package com.delivery.entity;
// Generated 07-15-2020 03:28:48 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "delivery")
public class Pedido implements java.io.Serializable {

	private Integer idPedido;
	private Personal personal;
	private String producto;
	private double precio;
	private String direccion;
	private List<Ruta> rutas = new ArrayList<Ruta>(0);

	public Pedido() {
	}

	public Pedido(Personal personal, String producto, double precio, String direccion) {
		this.personal = personal;
		this.producto = producto;
		this.precio = precio;
		this.direccion = direccion;
	}

	public Pedido(Personal personal, String producto, double precio, String direccion, List<Ruta> rutas) {
		this.personal = personal;
		this.producto = producto;
		this.precio = precio;
		this.direccion = direccion;
		this.rutas = rutas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_pedido", unique = true, nullable = false)
	public Integer getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(Integer idPedido) {
		this.idPedido = idPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_personal", nullable = false)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@Column(name = "producto", nullable = false, length = 150)
	public String getProducto() {
		return this.producto;
	}

	public void setProducto(String producto) {
		this.producto = producto;
	}

	@Column(name = "precio", nullable = false, precision = 18)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@Column(name = "direccion", nullable = false, length = 100)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public List<Ruta> getRutas() {
		return this.rutas;
	}

	public void setRutas(List<Ruta> rutas) {
		this.rutas = rutas;
	}

}
