package com.delivery.entity;
// Generated 07-15-2020 03:28:48 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Turno generated by hbm2java
 */
@Entity
@Table(name = "turno", catalog = "delivery")
public class Turno implements java.io.Serializable {

	private String idPersonal;
	private Personal personal;
	private String idTurno;

	public Turno() {
	}

	public Turno(Personal personal) {
		this.personal = personal;
	}

	public Turno(Personal personal, String idTurno) {
		this.personal = personal;
		this.idTurno = idTurno;
	}

	@GenericGenerator(name = "com.delivery.entity.TurnoIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personal"))
	@Id
	@GeneratedValue(generator = "com.delivery.entity.TurnoIdGenerator")

	@Column(name = "id_personal", unique = true, nullable = false, length = 10)
	public String getIdPersonal() {
		return this.idPersonal;
	}

	public void setIdPersonal(String idPersonal) {
		this.idPersonal = idPersonal;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@Column(name = "id_turno", length = 10)
	public String getIdTurno() {
		return this.idTurno;
	}

	public void setIdTurno(String idTurno) {
		this.idTurno = idTurno;
	}

}
