package com.delivery.entity;
// Generated 07-15-2020 03:28:48 PM by Hibernate Tools 5.2.12.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unidad generated by hbm2java
 */
@Entity
@Table(name = "unidad", catalog = "delivery")
public class Unidad implements java.io.Serializable {

	private String idUnidad;
	private Sucursal sucursal;
	private String modelo;
	private List<Motociclista> motociclistas = new ArrayList<Motociclista>(0);

	public Unidad() {
	}

	public Unidad(String idUnidad, Sucursal sucursal) {
		this.idUnidad = idUnidad;
		this.sucursal = sucursal;
	}

	public Unidad(String idUnidad, Sucursal sucursal, String modelo, List<Motociclista> motociclistas) {
		this.idUnidad = idUnidad;
		this.sucursal = sucursal;
		this.modelo = modelo;
		this.motociclistas = motociclistas;
	}

	@Id

	@Column(name = "id_unidad", unique = true, nullable = false, length = 9)
	public String getIdUnidad() {
		return this.idUnidad;
	}

	public void setIdUnidad(String idUnidad) {
		this.idUnidad = idUnidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sucursal", nullable = false)
	public Sucursal getSucursal() {
		return this.sucursal;
	}

	public void setSucursal(Sucursal sucursal) {
		this.sucursal = sucursal;
	}

	@Column(name = "modelo", length = 20)
	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unidad")
	public List<Motociclista> getMotociclistas() {
		return this.motociclistas;
	}

	public void setMotociclistas(List<Motociclista> motociclistas) {
		this.motociclistas = motociclistas;
	}

}
